version: '3.8'

services:
  node-app:
    container_name: node-app
    build: .
    networks:
      - webnotesNetwork
    ports:
      - "80:8080"
    restart: unless-stopped

  mongo-db:
    container_name: mongo-db
    image: mongo:4.4.17
    ports:
      - 27017:27017
    networks:
      - webnotesNetwork
    volumes:
      - webnotes_data:/data/db
    restart: unless-stopped

networks:
  webnotesNetwork:
    driver: bridge

volumes:
  webnotes_data: